version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: asyrafduyshart/nginx-custom-proxy
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build-tags:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:$CIRCLE_TAG -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-tags:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:$CIRCLE_TAG
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build-tags:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9A-z]+(\.[0-9A-z]+)*$/
      - publish-tags:
          requires:
            - build-tags
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9A-z]+(\.[0-9A-z]+)*$/
